CREATE TABLE IF NOT EXISTS bookmarks (
  user VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  short_url VARCHAR(32) NOT NULL,
  full_url VARCHAR(255) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (user, name),
  UNIQUE KEY short_url_uq (short_url),
  INDEX user_name_ix (user, name)
);

